### ISSUE TITLE
Problematically removes file encoding

### ISSUE THREAD

**Issue by wtyerogers** [ned14/automodinit#4]
At the beginning of my `__init__.py` I have a file encoding specified:
`# -*- coding: utf-8 -*-` as defined in [PEP 0263](https://www.python.org/dev/peps/pep-0263/)

Upon creating a new submodule & re-running, `automodinit` then does its job and re-writes parts of the `__init__.py` file. Problematically, this appears to include items that need to be within the first two lines according to Python:

> To define a source code encoding, a magic comment must
> be placed into the source files either as first or second
> line in the file (...)

This results in errors such as `SyntaxError: Non-ASCII character (...) but no encoding declared` when non-ASCII characters are in use.

I'm looking into the `automodinit` code to see if I can patch it for my local copy.

P.S. Love the `automodinit` package! Thank you :)

**Comment by wtyerogers** [comment]
Fixed locally.

Replaced:
```python
newmyself='__all__ = '+repr(modulefiles)+'\n'
```

with:

```python
newmyself=myself[:myself.find("__all__")]
newmyself+='__all__ = '+repr(modulefiles)+'\n'
```

so that anything preceding the first `__all__` will survive the re-write.

**Comment by ned14** [comment]
Fixed, thanks for the report.
